In [58]:
import pandas as pd
import matplotlib.pyplot as plt
import warnings

warnings.filterwarnings("ignore", category=UserWarning)

In [59]:
# trainデータの読み込み
df_train = pd.read_csv("/home/keiseki/JR_train_snow/20.Data/train.csv", encoding="cp932")
# 糸魚川駅、富山駅での通常車両の新幹線の車両への着雪量データであるフラグを付与
df_train["回送列車フラグ"] = 0

In [60]:
# 回送列車データの読み込み
df_through = pd.read_csv("/home/keiseki/JR_train_snow/20.Data/out_of_service.csv", encoding="cp932")
# 糸魚川駅、富山駅での回送車両への着雪量データであるフラグを付与
df_through["回送列車フラグ"] = 1

In [61]:
# 通常列車、回送列車のデータを結合
df_all = pd.concat([df_train, df_through], ignore_index=True)

In [62]:
# ダイヤ情報の読み込み
df_dia = pd.read_csv("/home/keiseki/JR_train_snow/20.Data/diagram.csv", encoding="cp932")
# df_dia

In [63]:
df_dia_T = df_dia.T
df_dia_T = df_dia_T.replace('↓', '通過')

df_dia_T.columns = df_dia_T.iloc[0]
df_dia_T = df_dia_T.iloc[1:]

# df_dia_T

In [64]:
# 列車情報とダイア情報を結合
df_all = pd.merge(df_all, df_dia_T, how='left', left_on='列車番号', right_index=True)
df_all

,年月日,列車番号,停車駅名,フェンダー部分(東京方向),台車部分,フェンダー部分(金沢方向),合計,回送列車フラグ,停車時刻,金沢,新高岡,富山,黒部宇奈月温泉,糸魚川,上越妙高,飯山,長野
0,2016-01-19,3500E,富山,0.000000,0.000000,0.000000,0.000000,0,NaN,6:00,通過,6:19,通過,通過,通過,通過,7:07
1,2016-01-19,562E,富山,0.000000,0.000000,0.000000,0.000000,0,NaN,11:56,12:10,12:19,12:32,12:46,12:59,通過,13:20
2,2016-01-19,560E,糸魚川,0.000000,0.000000,0.000000,0.000000,0,NaN,10:56,11:10,11:19,11:32,11:46,11:59,12:11,12:24
3,2016-01-19,560E,富山,0.000000,0.000000,0.002986,0.002986,0,NaN,10:56,11:10,11:19,11:32,11:46,11:59,12:11,12:24
4,2016-01-19,558E,糸魚川,0.000000,0.000000,0.000000,0.000000,0,NaN,9:21,9:35,9:45,9:57,10:11,10:25,10:37,11:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15334,2016-01-25,NaN,糸魚川,0.000048,0.002732,0.003908,0.006688,1,09:25:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15335,2016-01-25,NaN,糸魚川,0.000221,0.004932,0.005369,0.010521,1,08:30:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15336,2016-01-25,NaN,糸魚川,0.000136,0.005393,0.002608,0.008136,1,08:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15337,2016-01-25,NaN,糸魚川,0.002262,0.017006,0.000122,0.019390,1,07:42:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15338,2016-01-25,NaN,糸魚川,0.002535,0.009358,0.007220,0.019114,1,06:42:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [65]:
# 金沢着雪ゼロ列車
df_zero = pd.read_csv("/home/keiseki/JR_train_snow/20.Data/kanazawa_nosnow.csv", encoding="cp932", header=None, names=["列車番号"])

# df_zeroに記載されている列車番号に「金沢着雪ゼロ列車」フラグを付与
df_zero["金沢着雪ゼロ列車フラグ"] = 1
df_zero

     列車番号  金沢着雪ゼロ列車フラグ
0   2290E            1
1    552E            1
2   3502E            1
3   9536E            1
4    554E            1
5   2292E            1
6   3506E            1
7   3508E            1
8    560E            1
9    564E            1
10   566E            1
11   568E            1
12  8528E            1
13  8530E            1
14  3510E            1
15   572E            1
16  8532E            1
17  3512E            1
18  3514E            1
19  3516E            1
20   728E            1
21   734E            1

In [66]:
df_merge = pd.merge(df_all, df_zero, how='left', on='列車番号')
df_merge["金沢着雪ゼロ列車フラグ"] = df_merge["金沢着雪ゼロ列車フラグ"].fillna(0)
df_merge

,年月日,列車番号,停車駅名,フェンダー部分(東京方向),台車部分,フェンダー部分(金沢方向),合計,回送列車フラグ,停車時刻,金沢,新高岡,富山,黒部宇奈月温泉,糸魚川,上越妙高,飯山,長野,金沢着雪ゼロ列車フラグ
0,2016-01-19,3500E,富山,0.000000,0.000000,0.000000,0.000000,0,NaN,6:00,通過,6:19,通過,通過,通過,通過,7:07,0.0
1,2016-01-19,562E,富山,0.000000,0.000000,0.000000,0.000000,0,NaN,11:56,12:10,12:19,12:32,12:46,12:59,通過,13:20,0.0
2,2016-01-19,560E,糸魚川,0.000000,0.000000,0.000000,0.000000,0,NaN,10:56,11:10,11:19,11:32,11:46,11:59,12:11,12:24,1.0
3,2016-01-19,560E,富山,0.000000,0.000000,0.002986,0.002986,0,NaN,10:56,11:10,11:19,11:32,11:46,11:59,12:11,12:24,1.0
4,2016-01-19,558E,糸魚川,0.000000,0.000000,0.000000,0.000000,0,NaN,9:21,9:35,9:45,9:57,10:11,10:25,10:37,11:00,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15334,2016-01-25,NaN,糸魚川,0.000048,0.002732,0.003908,0.006688,1,09:25:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
15335,2016-01-25,NaN,糸魚川,0.000221,0.004932,0.005369,0.010521,1,08:30:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
15336,2016-01-25,NaN,糸魚川,0.000136,0.005393,0.002608,0.008136,1,08:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
15337,2016-01-25,NaN,糸魚川,0.002262,0.017006,0.000122,0.019390,1,07:42:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
15338,2016-01-25,NaN,糸魚川,0.002535,0.009358,0.007220,0.019114,1,06:42:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0

In [67]:
df_merge.to_pickle("/home/keiseki/JR_train_snow/20.Data/train_data_all.pkl")