In [5]:
import pandas as pd
import matplotlib.pyplot as plt
import warnings

warnings.filterwarnings("ignore", category=UserWarning)

---
風速計データの確認

In [6]:
# df_wind = pd.read_csv("/home/keiseki/JR_train_snow/20.Data/wind_location.csv", encoding='cp932', index_col=0)
# df_wind

---
気象データの確認

In [7]:
df_weather = pd.read_csv("/home/keiseki/JR_train_snow/20.Data/weather.csv", encoding='cp932', index_col=0)
df_weather

,地点,気温(℃),降水量(mm),降雪(cm),積雪(cm),日照時間(時間),風速(m/s),風向,日射量(MJ/㎡),現地気圧(hPa),海面気圧(hPa),相対湿度(％),蒸気圧(hPa),雲量(10分比),露点温度(℃),天気,視程(km)
年月日時,,,,,,,,,,,,,,,,,
2015/12/1 1:00,富山,9.4,2.0,0.0,0.0,0.0,1.4,西,0.0,1020.7,1022.8,86.0,10.1,NaN,7.2,NaN,NaN
2015/12/1 2:00,富山,9.0,0.5,0.0,0.0,0.0,1.7,南,0.0,1021.6,1023.7,88.0,10.1,NaN,7.1,NaN,NaN
2015/12/1 3:00,富山,9.1,0.0,0.0,0.0,0.0,0.6,西北西,0.0,1022.3,1024.4,89.0,10.3,10,7.4,10.0,10.0
2015/12/1 4:00,富山,8.8,0.5,0.0,0.0,0.0,1.7,北北西,0.0,1022.4,1024.5,88.0,10.0,NaN,6.9,NaN,NaN
2015/12/1 5:00,富山,8.5,0.0,0.0,0.0,0.0,1.7,南東,0.0,1022.5,1024.6,88.0,9.8,NaN,6.6,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2017/3/31 20:00,金沢,7.4,0.0,0.0,0.0,0.0,4.0,東北東,NaN,1013.7,1017.9,63.0,6.5,NaN,0.8,NaN,NaN
2017/3/31 21:00,金沢,7.5,0.0,0.0,0.0,0.0,5.0,東北東,NaN,1012.8,1016.9,63.0,6.5,10,0.9,4.0,15.0
2017/3/31 22:00,金沢,7.4,0.0,0.0,0.0,0.0,5.4,東北東,NaN,1012.4,1016.5,63.0,6.5,NaN,0.8,NaN,NaN
2017/3/31 23:00,金沢,7.4,0.0,0.0,0.0,0.0,5.1,東北東,NaN,1012.3,1016.4,62.0,6.4,NaN,0.6,NaN,NaN
2017/4/1 0:00,金沢,7.2,0.0,0.0,0.0,0.0,5.1,東北東,NaN,1011.8,1015.9,62.0,6.3,NaN,0.4,NaN,NaN

---
積雪計データの確認

In [9]:
df_snow_meter = pd.read_csv("/home/keiseki/JR_train_snow/20.Data/snowfall.csv", encoding='cp932', index_col=0)
df_snow_meter

                     積雪深(軌道)  積雪深(側溝)  積雪深(軌道A)  積雪深(軌道B)    地域名
年月日時
2015-12-01 00:00:00      NaN      NaN       NaN       NaN  富山野々上
2015-12-01 00:00:00      NaN      NaN       NaN       NaN    小矢部
2015-12-01 00:00:00      NaN      NaN       NaN       NaN    布施川
2015-12-01 00:00:00      NaN      NaN       NaN       NaN     朝日
2015-12-01 00:00:00      NaN      NaN       NaN       NaN    東金沢
...                      ...      ...       ...       ...    ...
2017-03-31 23:50:00    -22.0      0.0     -22.0     -22.0    梶屋敷
2017-03-31 23:50:00    -22.0      0.0     -22.0     -22.0   水橋白岩
2017-03-31 23:50:00    -22.0      0.0     -22.0     -22.0     津幡
2017-03-31 23:50:00    -22.0      0.0     -22.0     -22.0    田海川
2017-03-31 23:50:00    -22.0      0.0     -22.0     -22.0  高岡赤祖父

[349920 rows x 5 columns]